import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import RQProvider from "@/provider/rq"
import NuqsProvider from "@/provider/nuqs"
import MaterialProvider from "@/provider/material"
import IconSprite from "@/components/icons/icon-sprite"

import "@/styles/init.css"
import Header from "@/components/layout/Header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Material Products",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://cdn.dummyjson.com" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <MaterialProvider>
          <RQProvider>
            <NuqsProvider>
              <Header />
              {children}
            </NuqsProvider>
          </RQProvider>
        </MaterialProvider>
        <IconSprite />
      </body>
    </html>
  )
}
